[package]
name = "xyzen-relay-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "xyzen-relay"
path = "src/main.rs"

[dependencies]
xyzen-relay-proto = { path = "../proto" }
tokio.workspace = true
tokio-tungstenite.workspace = true
tokio-util.workspace = true
bytes.workspace = true
prost.workspace = true
futures-util.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
clap.workspace = true
